In [121]:
import pandas as pd
describe = ""
# load data
# all_df = pd.read_csv('y_image_data_allTogether_predict.csv')
side_df = pd.read_csv('y_image_data_side_predict.csv')
bottom_df = pd.read_csv('y_image_data_bottom_predict.csv')
y_df = pd.concat([side_df, bottom_df])
y_df = y_df.apply(lambda x: x.fillna(0) if x.dtype.kind in 'biufc' else x.fillna('.'))
# y_df = all_df
y_df

,Folder,ID,pred_side_12,pred_side_13,pred_side_14,pred_side_23,pred_side_24,pred_side_34,pred_side_all,pred_bottom_12,pred_bottom_13,pred_bottom_14,pred_bottom_23,pred_bottom_24,pred_bottom_34,pred_bottom_all
0,0005_loc-1_pine-side_01.jpg,5,2.0,3.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0005_loc-2_pine-side_02.jpg,5,1.0,1.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0005_loc-2_pine-side_04.jpg,5,1.0,1.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0008_loc-1_pine-side_01.jpg,8,2.0,3.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0008_loc-1_pine-side_02.jpg,8,2.0,3.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,0489_loc-1_pine-bottom_03.jpg,489,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,3.0,4.0,3.0,3.0
106,0489_loc-1_pine-bottom_04.jpg,489,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,3.0,4.0,3.0,3.0
107,0493_loc-2_pine-bottom_02.jpg,493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,3.0,4.0,3.0,4.0
108,0493_loc-2_pine-bottom_03.jpg,493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,3.0,4.0,3.0,4.0
109,0493_loc-2_pine-bottom_04.jpg,493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,3.0,4.0,3.0,4.0

In [122]:
# 創建一個新的 DataFrame
predict_df = pd.DataFrame(columns=['ID', 1, 2, 3, 4])

# 初始化新 DataFrame 的計數列
predict_df[[1, 2, 3, 4]] = 0
predict_df

Empty DataFrame
Columns: [ID, 1, 2, 3, 4]
Index: []

In [123]:

sideORbottomList = ["side", "bottom"]
versionList = ["12", "13", "14", "23", "24", "34", "all"]
# 遍歷每一行並計算加權計數
for index, row in y_df.iterrows():
    ID = row['ID']
    counts = {1: 0, 2: 0, 3: 0, 4: 0}

    # 計算加權計數
    for s in sideORbottomList:
        for version in versionList:
            col = f'pred_{s}_{version}'
            if row[col] != 0:
                # counts[row[col]] += 1
                if  4 == row[col]:
                    counts[row[col]] += 2
                    print(row[col])
                else:
                    counts[row[col]] += 1


    # 將結果添加到新的 DataFrame
    new_row = [ID, counts[1], counts[2], counts[3], counts[4]]
    predict_df.loc[len(predict_df)] = new_row
predict_df

4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0

      ID  1  2  3  4
0      5  1  2  4  0
1      5  3  1  3  0
2      5  3  1  3  0
3      8  1  2  4  0
4      8  1  2  4  0
..   ... .. .. .. ..
208  489  2  1  3  2
209  489  2  1  3  2
210  493  3  0  2  4
211  493  3  0  2  4
212  493  3  0  2  4

[213 rows x 5 columns]

In [124]:
# 按ID分組，並對每一列進行求和
grouped_df = predict_df.groupby('ID').sum().reset_index()
grouped_df

     ID   1   2   3   4
0     5  22   4  25  10
1     8  12  12  24   2
2    13  13   2  16   8
3    18  13   8  25   6
4    25  12   6   8   4
5    26  11   7  14   6
6    28   8   6  12   4
7    42   4   1   2   0
8    46   7   2   3   4
9    54   1   3   3   0
10   61   1   3   3   0
11   69   6   2   6   0
12   70  12   0   9  14
13   73  14   6   8   0
14   94   4   1   2   0
15  108   9   4   8   0
16  114  16   4   4   8
17  116  18  10  10   8
18  117   3   9   9   0
19  132  12   0   8  16
20  136   9   0   9   6
21  137  10   0   8   6
22  147  20   2  15  10
23  158  14   8  16   8
24  189   6   4   2   4
25  194   3   1   2   2
26  198   9   3   6   6
27  205   3   0   3   2
28  219   9   0   8   8
29  226   9   0   9   6
30  232   9   3   9   0
31  247   9   3   9   0
32  258   1   2   4   0
33  263   1   2   4   0
34  264   9   3   9   0
35  283   2   4   8   0
36  296  10   2  13   6
37  299  18   3  15  12
38  302   9   3   5   8
39  319  12   4  12   0
40  332   3   6  12   0
41  339  13   5  22   4
42  364  17   8  16   2
43  381  12   6  13   8
44  392  13   1   8  12
45  412  11   2  12   6
46  418  22  10  17   0
47  426  21  18  24   0
48  429   7   7   7   0
49  458   5  10  20   0
50  477  20  17  33   0
51  488   9   1   9   4
52  489   8   7  17   6
53  493  18   4  14  12

In [125]:
# 找到每行中值最大的列名稱
grouped_df['Classification Image'] = grouped_df[[1, 2, 3, 4]].idxmax(axis=1)
grouped_df

     ID   1   2   3   4  Classification Image
0     5  22   4  25  10                     3
1     8  12  12  24   2                     3
2    13  13   2  16   8                     3
3    18  13   8  25   6                     3
4    25  12   6   8   4                     1
5    26  11   7  14   6                     3
6    28   8   6  12   4                     3
7    42   4   1   2   0                     1
8    46   7   2   3   4                     1
9    54   1   3   3   0                     2
10   61   1   3   3   0                     2
11   69   6   2   6   0                     1
12   70  12   0   9  14                     4
13   73  14   6   8   0                     1
14   94   4   1   2   0                     1
15  108   9   4   8   0                     1
16  114  16   4   4   8                     1
17  116  18  10  10   8                     1
18  117   3   9   9   0                     2
19  132  12   0   8  16                     4
20  136   9   0   9   6                     1
21  137  10   0   8   6                     1
22  147  20   2  15  10                     1
23  158  14   8  16   8                     3
24  189   6   4   2   4                     1
25  194   3   1   2   2                     1
26  198   9   3   6   6                     1
27  205   3   0   3   2                     1
28  219   9   0   8   8                     1
29  226   9   0   9   6                     1
30  232   9   3   9   0                     1
31  247   9   3   9   0                     1
32  258   1   2   4   0                     3
33  263   1   2   4   0                     3
34  264   9   3   9   0                     1
35  283   2   4   8   0                     3
36  296  10   2  13   6                     3
37  299  18   3  15  12                     1
38  302   9   3   5   8                     1
39  319  12   4  12   0                     1
40  332   3   6  12   0                     3
41  339  13   5  22   4                     3
42  364  17   8  16   2                     1
43  381  12   6  13   8                     3
44  392  13   1   8  12                     1
45  412  11   2  12   6                     3
46  418  22  10  17   0                     1
47  426  21  18  24   0                     3
48  429   7   7   7   0                     1
49  458   5  10  20   0                     3
50  477  20  17  33   0                     3
51  488   9   1   9   4                     1
52  489   8   7  17   6                     3
53  493  18   4  14  12                     1

In [126]:
# 計算每個Classification voice的出現次數
classification_counts = grouped_df['Classification Image'].value_counts()
classification_counts

1    30
3    19
2     3
4     2
Name: Classification Image, dtype: int64

In [127]:
grouped_df.to_csv(f'final_{describe}.csv', index=False)